# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ysRpSDUlv8eRyvTCxTwvUXAaXtr94f2g
"""



import streamlit as st
import random

st.title('Test Streamlit')
st.write('Hello World!')

if st.button('Generate Random Number'):
  random_number = random.randint(1, 100)
  st.write(f'Random Number: {random_number}')

